export const gqlUrl = 'https://api.github.com/graphql'
export const gfmUrl = 'https://api.github.com/markdown'
export const ghUrl = 'https://github.com/ksuzu46'
export const ghUsername = 'ksuzu46'
export const myEmail = 'keisuke.suzuki46@gmail.com'
